apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-golang
  name: hello-golang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-golang
  template:
    metadata:
      labels:
        app: hello-golang
    spec:
      containers:
      - image: nobject/hello-golang:latest
        name: hello-golang
